### ISSUE TITLE
The regular expression to match the path and the value does not seems to work

### ISSUE THREAD

**Issue by HenrikGr** [jhenriquez/mongoose-mongodb-errors#5]
First, thank you for this plugin but I have tried it today and it does not seems to work due to that the regular expressions cause my server to crash.

Any ideas?

**Comment by HenrikGr** [comment]
I found it: :-)

Changed the one of them from:  
var path = err.message.match(/\$([\w]*)_\d/)[1]; 

to:
 var path = err.message.match(/([\w]*)_\d/)[1];

Then it worked for me.

**Comment by jhenriquez** [comment]
Thanks! I've been wanting to improve on it for some time. Would you please
put a PR for that? I'll review asap.

**Comment by HenrikGr** [comment]
I have not learned how to do PR yet. :-)

I did read the source code and implemented my own version that looks like this.

const mongoose = require('mongoose');
function errorHandler(err, doc, next) {
  if(err) {
    if (err.name === 'MongoError' && err.code === 11000) {
      const path = err.message.match(/([\w]*)_\d/)[1];
      const value = err.message.match(/\{\s:\s\"?([^\"\s]+)/)[1];
      const validationError = new mongoose.Error.ValidationError();
      validationError.errors[path] = validationError.errors[path] || {};
      validationError.errors[path].kind = 'duplicate';
      validationError.errors[path].value = value;
      validationError.errors[path].path = path;
      validationError.errors[path].message = '{0} is expected to be unique.'.replace('{0}', path);
      validationError.errors[path].reason = err.message;
      validationError.errors[path].name = err.name;
      next(validationError);
    }
    else {
      next(err);
    }
  }
  next();
}
function duplicateKeyError(schema) {
  schema.post('save', errorHandler);
  schema.post('update', errorHandler);
  schema.post('findOneAndUpdate', errorHandler);
  schema.post('insertMany', errorHandler);
}
module.exports = duplicateKeyError;

NOTE: I had problems when I had more validation rules in my model so I change that this plugin only checked for duplicate key errors, hence the if (err.name === 'MongoError' && err.code === 11000) 
change.

NOTE: I think it also should run even if it was no error hence the if(err) condition but I'm not sure about this? What do you think?

**Comment by jhenriquez** [comment]
I think this particular middlewares only run when an error occurs. But I'm
not 100% sure. I'd suggest you take a look at the documentation. I believe
they are called just like that, error middleware.
